// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type EditFlight struct {
	Name          *string `json:"name,omitempty"`
	DepartureTime *string `json:"departureTime,omitempty"`
	ArrivalTime   *string `json:"arrivalTime,omitempty"`
}

type Flight struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	DepartureTime string `json:"departureTime"`
	ArrivalTime   string `json:"arrivalTime"`
}

type FlightName struct {
	ID       string `json:"id"`
	FlightID string `json:"flightId"`
	Name     string `json:"name"`
}

type Mutation struct {
}

type NewFlight struct {
	Name          string `json:"name"`
	DepartureTime string `json:"departureTime"`
	ArrivalTime   string `json:"arrivalTime"`
}

type NewFlightName struct {
	FlightID string `json:"flightId"`
	Name     string `json:"name"`
}

type Query struct {
}
