CREATE TABLE IF NOT EXISTS FlightNames(
    ID INT NOT NULL UNIQUE AUTO_INCREMENT,
    FlightID INT NOT NULL,
    Name VARCHAR (127) NOT NULL UNIQUE,
    FOREIGN KEY (FlightID) REFERENCES Flights(ID) ,
    PRIMARY KEY (ID)
)
